### ISSUE TITLE
Use hlx.page as default

### ISSUE THREAD

**Issue by trieloff** [koraa/hlx-gh-action-purge-updated-cache#1]
https://github.com/koraa/hlx-gh-action-purge-updated-cache/blob/b62f779d658b7e4ebfe5b6389ec92325a828641c/index.js#L56

the outer CDN url should be optional

**Comment by koraa** [comment]
It needs some url; doesn't have to be outer…if you think this should be optional, please specify a way to determine the url in the other ticket. I'll close this one as this entire repo is in draft state.

https://github.com/adobe/helix-pages/issues/465

**Comment by koraa** [comment]
(Note: The specification should be a lot more vebose than "use hlx.page")
